import { wrapFunctional } from './utils'

export { default as BlockCard } from '../../components/BlockCard.vue'
export { default as DividerGeneral } from '../../components/DividerGeneral.vue'
export { default as JsonDetail } from '../../components/JsonDetail.vue'
export { default as MastheadSecondary } from '../../components/MastheadSecondary.vue'
export { default as ObjectDetail } from '../../components/ObjectDetail.vue'
export { default as ObjectImage } from '../../components/ObjectImage.vue'
export { default as PrimaryFooter } from '../../components/PrimaryFooter.vue'
export { default as PrimaryHeader } from '../../components/PrimaryHeader.vue'
export { default as SimpleCard } from '../../components/SimpleCard.vue'
export { default as SmartLink } from '../../components/SmartLink.vue'
export { default as TitleBlock } from '../../components/TitleBlock.vue'
